name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create build directory
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build with build-wrapper
        run: |
          cd build
          build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory cmake --build .

      - name: Run SonarCloud analysis
        run: |
          sonar-scanner
